files:
  - source: /core/res/res/values/serasa_strings.xml
    translation: /core/res/res/values-%android_code%/%original_file_name%
  - source: /packages/SystemUI/res/values/serasa_strings.xml
    translation: /packages/SystemUI/res/values-%android_code%/%original_file_name%
